# Generated by Django 4.0.5 on 2022-06-17 21:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=40, verbose_name='Ron en plantilla')),
            ],
        ),
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cancha', models.CharField(blank=True, choices=[('0', '5 vs 5'), ('1', '7 vs 7'), ('2', '9 vs 9'), ('2', '11 vs 11')], max_length=50, verbose_name='Tipo de cancha')),
                ('tipo_suelo', models.CharField(blank=True, choices=[('0', 'Pasto'), ('1', 'Sintético'), ('2', 'Piso')], max_length=50, verbose_name='Tipo de suelo')),
                ('remera_propia', models.BooleanField(default=False)),
                ('ciudad', models.CharField(max_length=255)),
                ('ubicacion', location_field.models.plain.PlainLocationField(max_length=63)),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, help_text='Describa brevemente que tipo de jugador/jugadores esta buscando')),
                ('fecha', models.DateTimeField(verbose_name='Fecha del partido')),
                ('posicion', models.ManyToManyField(to='categoria.subcategoria')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busqueda.rolplantilla')),
            ],
            options={
                'verbose_name': 'Busqueda',
                'verbose_name_plural': 'Busquedas',
                'ordering': ['fecha'],
            },
        ),
    ]
