# Generated by Django 4.0.4 on 2022-07-14 13:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0004_busqueda_jugadoresquefaltan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busqueda',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
