# Generated by Django 4.0.5 on 2022-06-17 16:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombres')),
                ('apellido', models.CharField(max_length=60, verbose_name='apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha de nacimiento')),
                ('sexo', models.CharField(choices=[('0', 'Femenino'), ('1', 'Masculino')], max_length=50, verbose_name='sexo')),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, help_text='Contanos sobre vos')),
                ('pie_habil', models.CharField(choices=[('0', 'Derecho'), ('1', 'Izquierdo'), ('2', 'Indistinto')], default='2', max_length=50, verbose_name='pie habil')),
                ('provincia', models.CharField(choices=[('0', 'Buenos Aires'), ('1', 'Cordoba'), ('2', 'Rosario')], default='Buenos Aires', max_length=50, verbose_name='provincia')),
                ('numero', models.IntegerField(blank=True, default=1, verbose_name='numero')),
                ('calle', models.CharField(default='vacio', max_length=100, verbose_name='calle')),
                ('localidad', models.CharField(blank=True, default='vacio', max_length=100, verbose_name='localidad')),
                ('categoria', models.ManyToManyField(to='categoria.subcategoria')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'apellido')},
            },
        ),
    ]
