# Generated by Django 4.0.5 on 2022-06-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='localidad',
            field=models.CharField(default='vacio', max_length=100, verbose_name='localidad'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='numero'),
        ),
    ]
