# Generated by Django 4.0.5 on 2022-06-19 21:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0002_alter_jugador_localidad_alter_jugador_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='numero',
        ),
        migrations.AlterField(
            model_name='jugador',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
