# Generated by Django 4.0.5 on 2022-06-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0003_remove_jugador_calle_remove_jugador_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='jugador'),
        ),
    ]
